# -*- coding: utf-8 -*-
"""prb1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyVDsZMGwr-7i2d8TtUtmSMIctXmTejw
"""

# Perform mathematical operations
a = 10
b = 5
print(f"Addition: {a + b}")

print(f"Subtraction: {a - b}")

print(f"Multiplication:{a * b}")

print(f"Division: {a / b}")