# -*- coding: utf-8 -*-
"""prb1.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyVDsZMGwr-7i2d8TtUtmSMIctXmTejw
"""

#Takeinput values and print output values
name = input("Enter your name: ")
age = input("Enter your age: ")

print("Hello! " + name + " You are " + age+ " years old.")