# -*- coding: utf-8 -*-
"""prb1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPf67KYUxUE9UCCQfvmP4fidX0n9ukby
"""

from collections import Counter

d1 = {'a': 100, 'b': 200, 'c': 300}
d2 = {'a': 300, 'b': 200, 'd': 400}

result = Counter(d1) + Counter(d2)

print(result)