# -*- coding: utf-8 -*-
"""prb2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120CRSoywatOIzQUOb7AK4W7MYJQnuLpz
"""

data = {'V': 10, 'VI': 10, 'VII': 40, 'VIII': 20, 'IX': 70, 'X': 80, 'XI': 40, 'XII': 20}

frequency_counts = {}

for value in data.values():
    if value in frequency_counts:
        frequency_counts[value] += 1
    else:
        frequency_counts[value] = 1

print("Original Dictionary:", data)
print("Frequency of the dictionary:", frequency_counts)