# -*- coding: utf-8 -*-
"""prb2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPf67KYUxUE9UCCQfvmP4fidX0n9ukby
"""

from collections import Counter

data = {'V': 10, 'VI': 10, 'VII': 40, 'VIII': 20, 'IX': 70, 'X': 80, 'XI': 40, 'XII': 20}

frequency_counts = Counter(data.values())

print("Original Dictionary:", data)
print("Frequency of the  dictionary:", frequency_counts)