# -*- coding: utf-8 -*-
"""prb3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPf67KYUxUE9UCCQfvmP4fidX0n9ukby
"""

def is_palindrome(text):
    text = text.lower().replace(" ", "")
    return text == text[::-1]

# Example usage
word = input("Enter a string: ")

if is_palindrome(word):
    print("Palindrome")
else:
    print("Not a palindrome")