# -*- coding: utf-8 -*-
"""prb4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPf67KYUxUE9UCCQfvmP4fidX0n9ukby
"""

def get_distinct_elements(input_list):

    return list(set(input_list))

sample_list = [1, 2, 3, 3, 3, 3, 4, 5]
output_list = get_distinct_elements(sample_list)

print("List :", sample_list)
print("Output :", output_list)