# -*- coding: utf-8 -*-
"""prb5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPf67KYUxUE9UCCQfvmP4fidX0n9ukby
"""

def print_distinct_counts(input_list):
    counts = {}
    for element in input_list:
        counts[element] = counts.get(element, 0) + 1

    for key, value in counts.items():
        print(f"{key} => {value}")

sample_list = [10, 20, 30, 30, 30, 30, 20, 40]
print_distinct_counts(sample_list)