# -*- coding: utf-8 -*-
"""prb6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPf67KYUxUE9UCCQfvmP4fidX0n9ukby
"""

starts_with = lambda string, sub: string.startswith(sub)

string = input("Enter a string: ")
sub = input("Enter a substring: ")

if starts_with(string, sub):
    print("The string starts with the given substring.")
else:
    print("The string does not start with the given substring.")