# -*- coding: utf-8 -*-
"""prb1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120CRSoywatOIzQUOb7AK4W7MYJQnuLpz
"""

sample_str = 'hello python'

words = sample_str.split(' ')
reversed_words = [word[::-1] for word in words]

result = ' '.join(reversed_words)

print(result)