# -*- coding: utf-8 -*-
"""prb2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120CRSoywatOIzQUOb7AK4W7MYJQnuLpz
"""

def is_palindrome(text):
    text = text.lower()

    return text == text[::-1]

test_str = str(input("Enter a string: ") )
if is_palindrome(test_str):
    print(f"'{test_str}' is a palindrome.")
else:
    print(f"'{test_str}' is NOT a palindrome.")