# -*- coding: utf-8 -*-
"""prb1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyVDsZMGwr-7i2d8TtUtmSMIctXmTejw
"""

#Problem1.
a = input("Enter value for a: ")
b = input("Enter value for b: ")

print(f"\nBefore swapping: a = {a}, b = {b}")

# Swapping the values
a, b = b, a

print(f"After swapping:  a = {a}, b = {b}")