# -*- coding: utf-8 -*-
"""prb3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyVDsZMGwr-7i2d8TtUtmSMIctXmTejw
"""

#Problem 3
num = int(input("Enter a number: "))

if num % 2 == 0:
    print(f"{num} is an Even number.")
else:
    print(f"{num} is an Odd number.")