# -*- coding: utf-8 -*-
"""prb4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyVDsZMGwr-7i2d8TtUtmSMIctXmTejw
"""

# Problem 4

char = input("Enter a character: ")
lower_char = char.lower()

if lower_char in ['a', 'e', 'i', 'o', 'u']:
    print(f"'{char}' is a Vowel.")
else:
    print(f"'{char}' is Not a Vowel.")