# -*- coding: utf-8 -*-
"""prb5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyVDsZMGwr-7i2d8TtUtmSMIctXmTejw
"""

# Problem 5

marks = int(input("Enter the student's marks: "))


if marks >= 90:
    grade = "A+"
elif marks >= 85:
    grade = "A"
elif marks >= 80:
    grade = "B+"
elif marks >= 75:
    grade = "B"
elif marks >= 70:
    grade = "C+"
elif marks >= 65:
    grade = "C"
elif marks >= 60:
    grade = "D+"
elif marks >= 50:
    grade = "D"
else:
    grade = "F"

# 3. Print the assigned grade
print(f"The grade for marks {marks} is: {grade}")