# -*- coding: utf-8 -*-
"""prb1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyVDsZMGwr-7i2d8TtUtmSMIctXmTejw
"""

fruits = ["apple", "banana", "cherry", "date"]

for fruit in fruits:
    print(f"I like to eat {fruit}s!")