# -*- coding: utf-8 -*-
"""prb2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120CRSoywatOIzQUOb7AK4W7MYJQnuLpz
"""

a = int(input("enter a digit: "))
while a >= 0:
  print(a)
  a-=1

print("All value printed")

