# -*- coding: utf-8 -*-
"""prb3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPf67KYUxUE9UCCQfvmP4fidX0n9ukby
"""

base = float(input("Enter the base number: "))
exponent = float(input("Enter the exponent: "))

result = base ** exponent

print("Result =", result)