# -*- coding: utf-8 -*-
"""prb4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPf67KYUxUE9UCCQfvmP4fidX0n9ukby
"""

total = 0

for num in range(2, 1000):
    is_prime = True

    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        total += num

print("Sum of all primes below 1000 =", total)