# -*- coding: utf-8 -*-
"""prb5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPf67KYUxUE9UCCQfvmP4fidX0n9ukby
"""

n = int(input("Enter the Number: "))

a, b = 0, 1

print(f"Fibonacci numbers below {n}:")

while a < n:
    print(a, end=" ")
    a, b = b, a + b